### ISSUE TITLE
redmine.project_membership.create internal error

### ISSUE THREAD

**Issue by anchiru** [maxtepkeev/python-redmine#121]
Hi Max,

I got a problem with redmine.project_membership.create
```
redmine = Redmine(redmine_url, requests={'verify': False}, key=redmine_key)
redmine.project_membership.create(project_id='test', user_id=264, role_ids=[6, 8])
```
output
```
File ".../venvs/redmine_api/lib/python3.4/site-packages/redmine/managers.py", line 184, in create
    response = self.redmine.request('post', url, data=data)
  File ".../venvs/redmine_api/lib/python3.4/site-packages/redmine/__init__.py", line 147, in request
    raise ServerError
redmine.exceptions.ServerError: Redmine returned internal error, perhaps you are doing something wrong
```
from redmine side
```
Started POST "/projects/test/memberships.json?key=..." for 127.0.0.1 at 2016-02-25 13:29:51 +0000
Processing by MembersController#create as JSON
  Parameters: {"key"=>"...", "project_id"=>"test"}
   (0.1ms)  SELECT MAX(`settings`.`updated_on`) FROM `settings`
  Token Load (0.1ms)  SELECT  `tokens`.* FROM `tokens` WHERE `tokens`.`action` = 'api' AND `tokens`.`value` = '...'  ORDER BY `tokens`.`id` ASC LIMIT 1
  User Load (0.1ms)  SELECT  `users`.* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`id` = ... LIMIT 1
  Current user: ... (id=...)
  Project Load (0.1ms)  SELECT  `projects`.* FROM `projects` WHERE `projects`.`identifier` = 'test' LIMIT 1
   (0.1ms)  SELECT `enabled_modules`.`name` FROM `enabled_modules` WHERE `enabled_modules`.`project_id` = 2
Completed 500 Internal Server Error in 10ms (ActiveRecord: 1.2ms)

NoMethodError (undefined method `valid?' for nil:NilClass):
  app/controllers/members_controller.rb:76:in `block (2 levels) in create'
  app/controllers/members_controller.rb:68:in `create'
```

> redmine 3.0.3
> python 3.4.3
> python-redmine 1.5.0

please help me. tnx

**Comment by anchiru** [comment]
please close this issue. it was a problem with Redmine Impasse plugin

**Comment by maxtepkeev** [comment]
Yes, when ``redmine.exceptions.ServerError`` is raised then in 99% cases there is something wrong with Redmine intself (bug, bad plugins etc.)

P.S. Sorry for the late reply, I was on vacation without internet access.
