### ISSUE TITLE
pyinstaller redmine.exceptions.ResourceError: Unsupported Redmine resource

### ISSUE THREAD

**Issue by manefesto** [maxtepkeev/python-redmine#139]
```
from redmine import *
import yaml

with open('config.yaml', 'r') as stream:
    cfg = yaml.load(stream)
redmine_obj = Redmine(cfg['host'], username=cfg['username'], password=cfg['password'], requests={'verify': False})
        redmine_obj.issue.create(project_id="test",
                             subject=u'test',
                             tracker_id=3,
                             description=u'test',
                             status_id=1,
                             priority_id=7,
                             assigned_to_id=311,
                             watcher_user_ids=[311],
                             start_date=strftime("%Y-%m-%d", localtime()),
                             due_date='',
                             estimated_hours=0,
                             done_ratio=0,
                             custom_fields=[
                                 {'id': 7, 'value': '311'},
                                 {'id': 15, 'value': ''}
                             ]
                             )
```
after build exe with pyinstaller,py2exe and other have error
```
Traceback (most recent call last):
  File "redmine_cli.py", line 6, in writeIssue
    issue = redmine_obj.issue.create(project_id="test",
  File "C:\bin\Python27\lib\site-packages\redmine\__init__.py", line 47, in __getattr__
    return ResourceManager(self, resource)
  File "C:\bin\Python27\lib\site-packages\redmine\managers.py", line 40, in __init__
    raise ResourceError
redmine.exceptions.ResourceError: Unsupported Redmine resource
```

local run py file work fine.
Do you have any ideas ?

**Comment by maxtepkeev** [comment]
This probably happens because of dynamic import in managers.py, as far as I know pyinstaller uses hidden-imports argument to resolve these, e.g.:

pyinstaller --hidden-import redmine.resources redmine_cli.py

**Comment by maxtepkeev** [comment]
I believe this can be closed.
