### ISSUE TITLE
ForbiddenError when calling redmine.user.all()

### ISSUE THREAD

**Issue by szhang24** [maxtepkeev/python-redmine#162]
I want to pull all the user on redmine. I tried:
>>>> redmine = Redmine('http://redmine.mill.co.uk', username='abcde', password='********')
>>>> users = redmine.user.all()
>>>> users[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mill3d/users/stevenz/virtualenvs/redmine_dev/lib/python2.7/site-packages/redmine/resultsets.py", line 93, in __getitem__
    return next(itertools.islice(self, item, item + 1))
  File "/mill3d/users/stevenz/virtualenvs/redmine_dev/lib/python2.7/site-packages/redmine/resultsets.py", line 102, in __iter__
    self._evaluate()
  File "/mill3d/users/stevenz/virtualenvs/redmine_dev/lib/python2.7/site-packages/redmine/resultsets.py", line 81, in _evaluate
    offset=self.manager.params.get('offset', self.offset)
  File "/mill3d/users/stevenz/virtualenvs/redmine_dev/lib/python2.7/site-packages/redmine/managers.py", line 62, in retrieve
    response = self.redmine.request('get', self.url, params=dict(self.params, limit=limit, offset=offset))
  File "/mill3d/users/stevenz/virtualenvs/redmine_dev/lib/python2.7/site-packages/redmine/__init__.py", line 134, in request
    raise ForbiddenError
redmine.exceptions.ForbiddenError: Requested resource is forbidden

Not sure if there's anything I did wrong. Or what's the right way of doing so? Thanks a lot!

**Comment by maxtepkeev** [comment]
Well, the error says it all, check that you've enabled REST API and check that the user you're using for API access has the needed permissions to access the user API endpoint. To be sure that everything works as expected use user with admin rights.
