### ISSUE TITLE
Cannot get users

### ISSUE THREAD

**Issue by LiuRuni** [maxtepkeev/python-redmine#192]
Hi, Max!
I want to get all users and projects, and here is my code.
```
# -*- coding: utf-8 -*-
from redminelib import Redmine
redmine = Redmine('http://redmine.houtai.com/', key='***')
users = redmine.user.all()
projects = redmine.project.all()
for u in users:
    print(u)
for p in projects:
    print(p)

```
After running, I can get the projects successfully, but cannot get the users. At the same time, an error is occured.

Traceback (most recent call last):
  File "C:\Python36-32\lib\site-packages\redminelib\engines\base.py", line 150, in process_response
    return response.json()
  File "C:\Python36-32\lib\site-packages\redminelib\packages\requests\models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python36-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\JetBrains\PyCharm 2017.1.5\helpers\pycharm\_jb_unittest_runner.py", line 35, in <module>
    main(argv=args, module=None, testRunner=unittestpy.TeamcityTestRunner, buffer=not JB_DISABLE_BUFFERING)
  File "C:\Python36-32\lib\unittest\main.py", line 93, in __init__
    self.parseArgs(argv)
  File "C:\Python36-32\lib\unittest\main.py", line 140, in parseArgs
    self.createTests()
  File "C:\Python36-32\lib\unittest\main.py", line 147, in createTests
    self.module)
  File "C:\Python36-32\lib\unittest\loader.py", line 219, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "C:\Python36-32\lib\unittest\loader.py", line 219, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "C:\Python36-32\lib\unittest\loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "E:\test01\test07.py", line 18, in <module>
    for u in users:
  File "C:\Python36-32\lib\site-packages\redminelib\resultsets.py", line 238, in __iter__
    return (self.manager.to_resource(resource) for resource in super(ResourceSet, self).__iter__())
  File "C:\Python36-32\lib\site-packages\redminelib\resultsets.py", line 107, in __iter__
    self._resources, self._total_count = self.manager.request(True)
  File "C:\Python36-32\lib\site-packages\redminelib\managers.py", line 56, in request
    return self.redmine.engine.bulk_request('get', self.url, self.container, **self.params)
  File "C:\Python36-32\lib\site-packages\redminelib\engines\base.py", line 88, in bulk_request
    response = self.request(method, url, params=dict(params, limit=limit or self.chunk, offset=offset))
  File "C:\Python36-32\lib\site-packages\redminelib\engines\base.py", line 75, in request
    return self.process_response(self.session.request(method, url, **kwargs), return_raw)
  File "C:\Python36-32\lib\site-packages\redminelib\engines\base.py", line 152, in process_response
    raise exceptions.JSONDecodeError(response)
redminelib.exceptions.JSONDecodeError: Unable to decode received JSON, you can inspect exception's "response" attribute to find out what the response was

Plese do me a favor with this question. Thank you!!

**Comment by maxtepkeev** [comment]
Hi,

Have a look at the last line, there's a hint about what you should do: `redminelib.exceptions.JSONDecodeError: Unable to decode received JSON, you can inspect exception's "response" attribute to find out what the response was`

**Comment by EmmaCode** [comment]
Hi, Max.

I tried to capture the HTTP request/response while ran the program, and found it's an invalid request from my IP. Now I am asking our developer to concern it.

Thank you!

**Comment by maxtepkeev** [comment]
I believe we can close this issue as there's no python-redmine's fault in what's going on.
