### ISSUE TITLE
localhost - Requested resource doesn't exist

### ISSUE THREAD

**Issue by dariomaim** [maxtepkeev/python-redmine#218]
### **Trying to use python-redmine on localhost server returns Requested resource doesn't exist**

```
from redminelib import Redmine

redmine = Redmine('http://localhost:8082', key='MY_KEY')

projects = redmine.project.all()

print(projects) # Connects to the api and retrieves and empty object

for project in projects:
    print(project) #There are projects in Redmine but none in retrieved object
```

<redminelib.resultsets.ResourceSet object with Project resources>
Traceback (most recent call last):
  File "api.py", line 9, in <module>
    for project in projects:
  File "/home/noviembre/Development/python/pyred/venvpyre/lib/python3.6/site-packages/redminelib/resultsets.py", line 278, in __iter__
    return (self.manager.to_resource(resource) for resource in super(ResourceSet, self).__iter__())
  File "/home/noviembre/Development/python/pyred/venvpyre/lib/python3.6/site-packages/redminelib/resultsets.py", line 115, in __iter__
    raise e
  File "/home/noviembre/Development/python/pyred/venvpyre/lib/python3.6/site-packages/redminelib/resultsets.py", line 111, in __iter__
    'get', self.manager.url, self.manager.container, **self.manager.params)
  File "/home/noviembre/Development/python/pyred/venvpyre/lib/python3.6/site-packages/redminelib/engines/base.py",line 89, in bulk_request
    response = self.request(method, url, params=dict(params, limit=limit or self.chunk, offset=offset))
  File "/home/noviembre/Development/python/pyred/venvpyre/lib/python3.6/site-packages/redminelib/engines/base.py",line 76, in request
    return self.process_response(self.session.request(method, url, **kwargs))
  File "/home/noviembre/Development/python/pyred/venvpyre/lib/python3.6/site-packages/redminelib/engines/base.py",line 157, in process_response
    raise exceptions.ResourceNotFoundError
redminelib.exceptions.ResourceNotFoundError: Requested resource doesn't exist

### **Same code on production server, works ok. So it is probably config issue, any ideas for workaround/fix? :) **

**Comment by maxtepkeev** [comment]
It is most likely a config issue on the Redmine side and not on the Python-Redmine side, try to load the following URL in your browser and see if there's a JSON output with the projects: ``http://localhost:8082/projects.json``

**Comment by dariomaim** [comment]
I already tested http://localhost:8082/projects.json, there is a json with the projects so it should be a config issue. Thanks!
