### ISSUE TITLE
unable to update issue

### ISSUE THREAD

**Issue by dadokkio** [maxtepkeev/python-redmine#223]
Hi,
I'm able to create new issues in a project and search with redmine.issue.all() all the open issues. 
But, when I try to update one issue the api return this error:
```
>>> redmine
<redminelib.Redmine object at 0x0000000002572860>
>>> redmine.issue.get(247006)
<redminelib.resources.Issue #247006 "#cavapotami2">
>>> redmine.issue.update(247006, description='Work tasks')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\envs\bot\lib\site-packages\redminelib\managers\base.py", line 221, in update
    response = self.redmine.engine.request(self.resource_class.http_method_update, url, data=request)
  File "C:\Anaconda3\envs\bot\lib\site-packages\redminelib\engines\base.py", line 76, in request
    return self.process_response(self.session.request(method, url, **kwargs))
  File "C:\Anaconda3\envs\bot\lib\site-packages\redminelib\engines\base.py", line 153, in process_response
    raise exceptions.AuthError
redminelib.exceptions.AuthError: Invalid authentication details
```

Also the save functionality returns the same error:

```
>>> issue = redmine.issue.get(247006)
>>> issue.description
'ip+=8.8.8.8\r\nip+=4.4.4.4\r\nzone+=dmz\r\ndescription=tegolino\r\ncapability+=cioccolato\r\ntype+=senza glutine\r\ndomain name+=google.com\r\ndomain
 name+=pippo.com\r\nhash+=jdsahjdashudjsa\r\nregistry key+=jrejewqhjrwqh/fdsaads/saddsa\r\npath+=das/dasdsa/dasasd\r\njkfdhjkfdskjhfdskj\r\ndsfaklfkds
llkjdsfjklhf\r\nkgfdskjlhsdflkjh'
>>> issue.description = "ciao"
>>> issue.save()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\envs\bot\lib\site-packages\redminelib\resources\base.py", line 368, in save
    self.manager.update(self.internal_id, **self._changes)
  File "C:\Anaconda3\envs\bot\lib\site-packages\redminelib\managers\base.py", line 221, in update
    response = self.redmine.engine.request(self.resource_class.http_method_update, url, data=request)
  File "C:\Anaconda3\envs\bot\lib\site-packages\redminelib\engines\base.py", line 76, in request
    return self.process_response(self.session.request(method, url, **kwargs))
  File "C:\Anaconda3\envs\bot\lib\site-packages\redminelib\engines\base.py", line 153, in process_response
    raise exceptions.AuthError
redminelib.exceptions.AuthError: Invalid authentication details
```

There is something I'm missing? 
At the moment I'm using the http://demo.redmine.org website so I'm not sure if some functionality are unavailable on that site.

Thanks.

**Comment by maxtepkeev** [comment]
Hi @dadokkio 

I'm in no way affiliated with demo.redmine.org but as far as I remember part of the functionality is only available if you register an account there, I suggest you to test against http://demo.redmineup.com, the login and password is admin

**Comment by dadokkio** [comment]
Thanks, on redmineup everything works properly
```
>>> a = redmine.issue.all()[0]
>>> a.description = "WTF"
>>> a.save()
<redminelib.resources.Issue #605 "???????? ???">
>>> a = redmine.issue.all()[0]
>>> a.description
'WTF'
>>>
```
