### ISSUE TITLE
OpenProject support?

### ISSUE THREAD

**Issue by The-Alchemist** [maxtepkeev/python-redmine#239]
I was wondering if anyone has tried using python-redmine with OpenProject, a fork of Redmine.  I get a lot of :

```
>>> redmine.project.get('project_name')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/redminelib/managers/base.py", line 83, in get
    return self.to_resource(self.redmine.engine.request('get', self.url, params=self.params)[self.container])
KeyError: 'project'

```

**Comment by maxtepkeev** [comment]
Hi,

I've checked their API docs and they've changed A LOT. They not only changed the response structure, they're also using hal+json instead of just json, so Python-Redmine will not work out of the box, a lot of work has to be done to make Python-Redmine work with OpenProject.
