### ISSUE TITLE
redminelib installation problem

### ISSUE THREAD

**Issue by fcabaud** [maxtepkeev/python-redmine#241]
Hello,

I'm on Ubuntu 19.10, in a pipenv with python 3.6.
When I install redminelib I got this error

`pip install redminelib
Traceback (most recent call last):
  File "/home/frederic/.local/share/virtualenvs/scripts-FkKjGb8A/bin/pip", line 6, in <module>
    from pip._internal import main
  File "/home/frederic/.local/share/virtualenvs/scripts-FkKjGb8A/lib/python3.6/site-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/frederic/.local/share/virtualenvs/scripts-FkKjGb8A/lib/python3.6/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/frederic/.local/share/virtualenvs/scripts-FkKjGb8A/lib/python3.6/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/frederic/.local/share/virtualenvs/scripts-FkKjGb8A/lib/python3.6/site-packages/pip/_internal/cli/cmdoptions.py", line 15, in <module>
    from distutils.util import strtobool
  File "/home/frederic/.local/share/virtualenvs/scripts-FkKjGb8A/lib/python3.6/distutils/__init__.py", line 44, in <module>
    from distutils import dist, sysconfig  # isort:skip
ImportError: cannot import name 'dist'
`

**Comment by maxtepkeev** [comment]
Hi,

We're testing against Python 3.6 and 3.7 and haven't experienced this issue. This must be Ubuntu specific and probably can be solved with something like ``sudo apt install python3-distutils``

**Comment by fcabaud** [comment]
It was a problem of pipenv installation.
My Fault.
