### ISSUE TITLE
Unsupported Redmine resource

### ISSUE THREAD

**Issue by duaneellissd** [maxtepkeev/python-redmine#292]
Using the example code from the readme, like this:

```python
import redminelib

import sys
import json
from redminelib import Redmine
from dateutil.relativedelta import relativedelta

with open('config.json', 'r') as f:
    cfg = json.load(f)
    
server = Redmine(url=cfg['url'], key=cfg['key'])
pall = server.projects.get('GSDR')

print("pall = %s" % dir(pall))
sys.exit(1)
```

I get the following error:
```
Traceback (most recent call last):
  File "C:\Users\dellis\AppData\Roaming\Python\Python36\site-packages\redminelib\__init__.py", line 62, in __getattr__
    resource_class = resources.registry[resource_name]['class']
KeyError: 'Projects'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ticket-maker.py", line 13, in <module>
    pall = server.projects.get('GSDR')
  File "C:\Users\dellis\AppData\Roaming\Python\Python36\site-packages\redminelib\__init__.py", line 64, in __getattr__
    raise exceptions.ResourceError
redminelib.exceptions.ResourceError: Unsupported Redmine resource

```
Seems like no matter what I do - I get this Exception. - I'm stuck.

in #139 - This occurs after creating an EXE - I'm not doing that - I'm just executing the python script
In issue #99 - it basically says, go read the docs on https://python-redmine.readthedocs.io/
But that site is DEAD - you end up at an ASCII ART Maze picture.

**Comment by duaneellissd** [comment]
Answering my own question:, keyerror: "Projects" (plural) - it is actually singular

GRR - this is not a forgiving API!

**Comment by alxmoroz** [comment]
Docs are here: https://python-redmine.com/ as noted in README for now)

**Comment by maxtepkeev** [comment]
Seems like the issue is solved.
