### ISSUE TITLE
Redmine.attachment.get method raises JSONDecodeError

### ISSUE THREAD

**Issue by Crispy13** [maxtepkeev/python-redmine#313]
```
redmine = Redmine(blah)
redmine.attachment.get(6231)
```

raises a JSONDecodeError

```
2023-01-27 09:12:00,423    
Traceback (most recent call last):
  File "/software/anaconda3/envs/GM/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/anaconda3/envs/GM/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/anaconda3/envs/GM/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/anaconda3/envs/GM/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/software/anaconda3/envs/GM/lib/python3.11/site-packages/redminelib/engines/base.py", line 161, in process_response
    return response.json()
           ^^^^^^^^^^^^^^^
  File "/software/anaconda3/envs/GM/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/software/anaconda3/envs/GM/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3442, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_1596898/646578575.py", line 1, in <module>
    redmine.attachment.get(6231)
  File "/software/anaconda3/envs/GM/lib/python3.11/site-packages/redminelib/managers/base.py", line 99, in get
    response = self.redmine.engine.request('get', self.url, params=self.params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/anaconda3/envs/GM/lib/python3.11/site-packages/redminelib/engines/base.py", line 83, in request
    return self.process_response(self.session.request(method, url, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/anaconda3/envs/GM/lib/python3.11/site-packages/redminelib/engines/base.py", line 163, in process_response
    raise exceptions.JSONDecodeError(response)
redminelib.exceptions.JSONDecodeError: Unable to decode received JSON, you can inspect exception's "response" attribute to find out what the response was
```

The attachment file is an excel file (xlsx) and the error's reponse was 200.

How could I solve this?

**Comment by maxtepkeev** [comment]
Hi @Crispy13 

We need to check what the actual response from Redmine is, you can do that easily without programming by opening the following URL in your browser:

http(s)://your-redmine-url/attachments/X.json

Where X is the ID of the attachment you're trying to get (I assume it's 6231 according to your code). Be sure to login in to Redmine with the same credentials you used to access the API with Python-Redmine.

**Comment by Crispy13** [comment]
I'm sorry to be here late
With the address, I got a excel preview page.

**Comment by Crispy13** [comment]
> @Crispy13 if you're getting an excel document when requesting an url ending with .json there's definitely something wrong with your redmine instance, most likely you have a plugin that's doing that. Do you have any 3rd party plugins installed and can you try disabling them one by one and checking that url until you get a proper json response ?

Unfortunately, I don't have access to the plugins in the site. So I can't inspect it. Close this until I have some information about what you said.
