### ISSUE TITLE
Get member users from project_membership

### ISSUE THREAD

**Issue by denis-tzdm** [maxtepkeev/python-redmine#340]
Hello! I'm trying to get users which are members of a project. I do it like this:
```python
membership = list(redmine.project_membership.filter(project_id=1))
users = [m.user for m in membership]
```
I get error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.12/site-packages/redminelib/resources/base.py", line 223, in __getattr__
    raise exceptions.ResourceAttrError
redminelib.exceptions.ResourceAttrError: Resource doesn't have the requested attribute
```

`membership[0].user` returns `redminelib.resources.User` object, no errors.
How do I get membership attribute in loop?

**Comment by maxtepkeev** [comment]
Hi @denis-tzdm 

Most likely because some of your membership objects don't have a user object, because it's not necessary to have one, there can also be a group object instead of a user object. Just add an if statement to your list comprehension if you need only users and not groups.

Also it's not necessary to put list() around list(redmine.project_membership.filter(project_id=1)) because it' iterable by itself, so you're doing iteration twice.

**Comment by denis-tzdm** [comment]
@maxtepkeev thank you so much! I somehow missed that there can be a group instead of a user.
