### ISSUE TITLE
UnicodeDecodeError in install with LC_ALL=C

### ISSUE THREAD

**Issue by spikergit1** [maxtepkeev/python-redmine#90]

**Comment by spikergit1** [comment]
Woops, submitted too fast.

Same issue as https://github.com/gabrielfalcao/HTTPretty/issues/223

```
ERROR: invocation failed (exit code 1), logfile: /home/vagrant/trunk/.tox/py34/log/py34-2.log
ERROR: actionid: py34
msg: installpkg
cmdargs: [local('/home/vagrant/trunk/.tox/py34/bin/pip'), 'install', '--upgrade', '/home/vagrant/trunk/.tox/dist/redmine-1.0.post0.zip']
env: {'LC_ALL': 'C', 'PYTHONHASHSEED': '2415528924', 'PATH': '/home/vagrant/trunk/.tox/py34/bin:/home/vagrant/trunk/venv3/bin:/home/vagrant/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games', 'VIRTUAL_ENV': '/home/vagrant/trunk/.tox/py34'}

Processing ./.tox/dist/redmine-1.0.post0.zip
Collecting python-redmine (from redmine==1.0.post0)
  This repository located at pypi is not a trusted host, if this repository is available via HTTPS it is recommend to use HTTPS instead, otherwise you may silence this warning with '--trusted-host pypi'.
  DEPRECATION: Implicitly allowing locations which are not hosted at a secure origin is deprecated and will require the use of --trusted-host in the future.
  Using cached python-redmine-1.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-usq3zo_r/python-redmine/setup.py", line 37, in <module>
        long_description=open('README.rst').read() + '\n\n' + open('CHANGELOG.rst').read(),
      File "/home/vagrant//trunk/.tox/py34/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3906: ordinal not in range(128)

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-usq3zo_r/python-redmine
```

**Comment by spikergit1** [comment]
This issue is not only when using tox.  It affects any installation with LC_ALL=C
```
(venv3) $ LC_ALL=C pip install -I python-redmine
Collecting python-redmine
  This repository located at pypi is not a trusted host, if this repository is available via HTTPS it is recommend to use HTTPS instead, otherwise you may silence this warning with '--trusted-host pypi'.
  DEPRECATION: Implicitly allowing locations which are not hosted at a secure origin is deprecated and will require the use of --trusted-host in the future.
  Using cached python-redmine-1.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-rru1ev4z/python-redmine/setup.py", line 37, in <module>
        long_description=open('README.rst').read() + '\n\n' + open('CHANGELOG.rst').read(),
      File "/home/vagrant/venv3/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3906: ordinal not in range(128)

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rru1ev4z/python-redmine
(venv3) $
```

**Comment by maxtepkeev** [comment]
Thanks for investigating and fixing this. I have to be more careful with unicode symbols.
