### ISSUE TITLE
Unsupported redmine resource

### ISSUE THREAD

**Issue by danpilch** [maxtepkeev/python-redmine#99]
Whenever I attempt to use:

            list = redmine.managers.ResourceManager.all()

I receive:

Traceback (most recent call last):
  File "/usr/bin/redmine", line 79, in <module>
    main()
  File "/usr/bin/redmine", line 75, in main
    redmine.list_users()
  File "/usr/bin/redmine", line 60, in list_users
    list = redmine.managers.ResourceManager.filter(9)
  File "/usr/lib/python2.6/site-packages/redmine/__init__.py", line 45, in __getattr__
    return ResourceManager(self, resource)
  File "/usr/lib/python2.6/site-packages/redmine/managers.py", line 38, in __init__
    raise ResourceError
redmine.exceptions.ResourceError: Unsupported redmine resource

Any ideas?

**Comment by maxtepkeev** [comment]
Hi,

Why are you doing this ?

It looks like you didn't read the documentation, because you're using python-redmine in an absolutely wrong way.

Please, have a look at the [docs](http://python-redmine.readthedocs.org) before using it.

**Comment by maxtepkeev** [comment]
Closed due to inactivity, if you still need help, let me know, and I'll reopen it.
